# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a161ec033dc52a14ff5bfa8d13fccd4419cc788721f7eeecc2d731326d0210b64339d082c339d5516adf3564e5dd426066ec6d4087c428da84ece174ab885252

test:
  secret_key_base: f4ea43d473343a6ed6f86915af4565192b4c50661ef11845385af7a8104daf0d9610a5b3a9e91db01d188619ddb8344cce90b07cd2baf4511da0788255312bc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
